<div class="card my-2">
    <div class="picture-author d-flex align-items-center pb-2 p-3">
        <a href="profile.php?id=<?=$author->getUserID()?>" class="author">
            <?= $author->getUsername() ?>
        </a>
    </div>
    <div class="d-flex justify-content-center">
        <button class="btn btn-danger btn-sm delete-pic <?=$isPictureAuthor ? 'd-inline' : 'd-none'?>" data-picture="<?=$picture->getPictureId()?>"><i class="fas fa-trash"></i></button>
        <img class="card-img-top picture" src="<?= htmlspecialchars($picture->getPicturePath()) ?>" alt="">
    </div>
    <div class="card-body">
        <div class="reactions">
            <div class="row">
                <div class="col-auto">
                    <button class="btn btn-sm btn-success upvote" data-picture="<?php echo $picture->getPictureId()?>"><i class="fas fa-arrow-up"></i></button>
                </div>
                <div class="col">
                    <span class="upvote-count text-success float-left"><?= $upvoteCount?></span>
                    <span class="downvote-count text-danger float-right"><?= $downvoteCount?></span>
                </div>
                <div class="col-auto">
                    <button class="btn btn-sm btn-danger downvote" data-picture="<?php echo $picture->getPictureId()?>"><i class="fas fa-arrow-down"></i></button>
                </div>
            </div>
        </div>
        <p class="card-text description mt-2" style="font-size: 9pt; color: #888;"> <?= htmlspecialchars($picture->getDescription()) ?> </p>
        <hr />
        <div class="form-group">
            <div class="input-group">
                <input placeholder="Comment on this post" class="form-control" />
                <div class="input-group-append">
                    <button class="btn btn-primary comment-btn" data-picture="<?php echo $picture->getPictureId()?>"><i class="fas fa-comment"></i></button>
                </div>
            </div>
        </div>
        <div class="all-comments">
        <?php
        for($i=0; $i<count($comments); $i++){
            $user = $comments[$i]['user'];
            $userID = $user->getUserId();
            echo "<div class='comment'>";
            echo "<a href='profile.php?id=$userID' class='author d-inline'>";
            echo htmlspecialchars($comments[$i]['user']->getUsername()) . " " ."</a>";
            echo "<p class='comment-content d-inline'>";
            echo htmlspecialchars($comments[$i]['comment']->getContent()) . "</p>";
            echo "</div>";
        }
        ?>
        </div>
    </div>
</div>
